- hosts: all
  become: true
  tasks:
    - name: Remover script de instalação do NodeSource, se existir
      file:
        path: /tmp/node_setup.sh
        state: absent

    - name: Baixar script de instalação do NodeSource
      uri:
        url: https://rpm.nodesource.com/setup_14.x
        dest: /tmp/node_setup.sh

    - name: Executar script de instalação do NodeSource
      command: sudo bash /tmp/node_setup.sh

    - name: Instalar Node.js e npm
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - npm

    - name: Instalar PM2 globalmente
      npm:
        name: pm2
        global: yes
        state: present

    - name: Instalar Git
      package:
        name: git
        state: present


    - name: Clonar repositório do GitHub
      git:
        repo: https://github.com/Jackson-SM/Hockey-Desafio.git
        dest: /tmp/landing-page

    - name: Abrir porta 8080
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled

    - name: Expor aplicação com PM2
      command: pm2 serve /tmp/landing-page --port 8080 -f
